FROM python:3.12-slim
WORKDIR /app/user_agent
COPY requirements_minimal.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
COPY main_minimal.py main.py
EXPOSE 8088
CMD ["python", "main.py"]
